### ISSUE TITLE
segfault after compiling

### ISSUE THREAD

**Issue by ppkn** [ehrenbrav/FCEUX_Learning_Environment#1]
When I run `./fceux` in the `src` folder I get `segmentation fault (core dumped)`
I'm running elementaryOS 0.4 which is built on Ubuntu 16.04

Do you have an idea of how to get around this?

**Comment by ehrenbrav** [comment]
The fceux by default is compiled as a shared library - I don't think it
would run as a stand-alone executable.

What you need to do is set the MAKE_LIB environment variable to 0 - then it
will compile an executable rather than a library.

Please pull my latest code from the 'eb' branch (I had to fix a bug for
this to work), and in the main project directory run `scons MAKE_LIB=0` to
compile. Then in the src/ directory, run `./fceux <path-to-your-rom>` and
that should do it.

Let me know if that doesn't work for you...

**Comment by ppkn** [comment]
It's working now! Thanks 😄
